### ISSUE TITLE
Getting 0 for redis_memory_used_bytes

### ISSUE THREAD

**Issue by shubhambhattar** [oliver006/redis_exporter#386] opened 2020-05-18 19:03 UTC
**Describe the problem**
We're noticing that momentarily `redis-exporter` container will report `0` as the value for `redis_memory_used_bytes` for Redis servers. Any idea why this could be happening?

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
Version: v1.5.2

**Running the exporter**
Redis Exporter is running as a sidecar container to Redis Pod running as a StatefulSet in Kubernetes (Azure Kubernetes Service).

**Screenshots**
[https://imgur.com/a/udsmbmk](https://imgur.com/a/udsmbmk)

**Comment by oliver006** [comment] 2020-05-18 23:35
Thanks for raising this issue.

I have not observed such an issue, could it be possible that your Prometheus server failed to scrape the exporter when you observe that?

**Comment by shubhambhattar** [comment] 2020-05-19 09:01
[https://imgur.com/a/seaB9Lg](https://imgur.com/a/seaB9Lg)

Hi @oliver006, only `redis_memory_used_bytes` goes `0`. The other metrics are available for the time frame.
I guess if Prometheus server failed to scrape, metrics should disappear in all the graphs, right?

**Comment by oliver006** [comment] 2020-05-19 13:43
That's a good point. Can you confirm that the value is indeed zero and not just missing ?

I've not observed this issue myself so not sure how to further dig into this but you could run in verbose mode and see what the `INFO` result was at the time of the metric being reported as zero.

**Comment by shubhambhattar** [comment] 2020-05-19 17:16
The value is `0` but I also checked the Visualization Tab in where Null values were set to show as `0`. 

I changed the config to see `null` as breaks in the graph, and the graph is actually broken, i.e., no value is present for that time frame.

Also, wanted to ask that redis_exporter is also just querying the redis memory usage so if there is a long running command which blocked Redis for some time, you won't get a response for your query right away. In that case, will I get breaks in graphs?

[https://imgur.com/a/bL1vLIY](https://imgur.com/a/bL1vLIY)

**Comment by shubhambhattar** [comment] 2020-05-19 17:28
Continuing my above comment, the gap that you see starts at 6:31 and ends at 6:33 IST (IST = GMT + 5:30) which converted to GMT will be `[1:31, 1:33]`. I checked the STDOUT logs of Redis Exporter and found this:

```
time="2020-05-19T01:01:04Z" level=error msg="Couldn't connect to redis instance"
time="2020-05-19T01:01:34Z" level=error msg="Couldn't connect to redis instance"
time="2020-05-19T01:02:04Z" level=error msg="Couldn't connect to redis instance"
```

**Comment by oliver006** [comment] 2020-05-19 18:12
Great find, thanks @shubhambhattar 

Normally the connection error string isn't logged (to avoid leaking secrets) but you can enable verbose mode and it should get logged.

`long running command which blocked Redis for some time` - not 1oo% sure but something you can simulate/try by using the `DEBUG SLEEP X` command.

**Comment by shubhambhattar** [comment] 2020-05-19 18:42
@oliver006 I am trying to simulate this in my local. I ran a Redis and redis_exporter container in my local machine.

I ran the Redis container with:

```
docker run -it -p 6379:6379 redis:5
```

- Can you tell me how to enable verbose mode logs in redis_exporter? I ran redis_exporter with the following command:
    ```
    docker run -it -p 9121:9121 oliver006/redis_exporter
    ```

- Is the data available at my `localhost:9121` going to be any useful here?

**Comment by oliver006** [comment] 2020-05-19 18:47
Not sure if running locally will let you reproduce this as I don't know the details of your system.

Pass the  `--debug` flag to the exporter, that'll enable verbose output.

**Comment by shubhambhattar** [comment] 2020-05-19 18:47
@oliver006 Also, wanted to ask if `nullPointMode` set as `connected` in this: https://github.com/oliver006/redis_exporter/blob/master/contrib/grafana_prometheus_redis_dashboard.json intentional? Should it be changed to `null` in that file?

**Comment by shubhambhattar** [comment] 2020-05-19 18:56
I am trying to check if a long running command can reproduce the error log that I posted in this comment: [https://github.com/oliver006/redis_exporter/issues/386#issuecomment-630966013](https://github.com/oliver006/redis_exporter/issues/386#issuecomment-630966013)

Hence, running it in my local machine. 

I've also enabled debug logs but I am not getting anything after the initial start of redis_exporter. Like, its not issuing any commands to REDIS. This is the log that I get in redis_exporter:

```
INFO[0000] Redis Metrics Exporter v1.6.1    build date: 2020-05-13-02:16:26    sha1: 34c779deb5f9a1e023166b5cf3717d53cdc97053    Go: go1.14.2    GOOS: linux    GOARCH: amd64 
DEBU[0000] Enabling debug output                        
DEBU[0000] NewRedisExporter options: main.Options{Password:"", Namespace:"redis", ConfigCommandName:"CONFIG", CheckSingleKeys:"", CheckKeys:"", LuaScript:[]uint8(nil), ClientCertificates:[]tls.Certificate(nil), InclSystemMetrics:false, SkipTLSVerification:false, SetClientName:true, IsTile38:false, ExportClientList:false, ConnectionTimeouts:15000000000, MetricsPath:"/metrics", RedisMetricsOnly:false, PingOnConnect:false, Registry:(*prometheus.Registry)(0xc0000b26e0)} 
DEBU[0000] keys: []main.dbKeyPair(nil)                  
DEBU[0000] singleKeys: []main.dbKeyPair(nil)            
INFO[0000] Providing metrics at :9121/metrics           
DEBU[0000] Configured redis addr: "redis://localhost:6379" 



```
Am I missing something here? Exporter is not doing anything after startup.
Also, no timestamps are showing. Is this normal?

**Comment by oliver006** [comment] 2020-05-19 19:10
That's correct. The exporter doesn't do any scraping until the `/metrics` endpoint is being hit.

**Comment by shubhambhattar** [comment] 2020-05-19 19:20
Okay, so I forgot that `redis_exporter`'s localhost is not `redis` container. Running these 2 commands finally:
```
$ docker run --rm -p 6379:6379 --name redis redis:5
```
and 
```
docker run --rm -p 9121:9121 --name redis_exporter oliver006/redis_exporter:alpine --redis.addr 172.17.0.2 --debug
``` 
(I checked Redis container's IP is `172.17.0.2`).
Then, I hit `localhost:9121` as you suggested and got the response. Was even able to monitor the command run on Redis using `monitor`.

After these, I connected to `redis-cli`, issued an `DEBUG SLEEP 100` command and immediately hit `localhost:9121` and got the following DEBUG logs in `redis_exporter` (that you wanted):

```
time="2020-05-19T19:17:33Z" level=debug msg="Trying DialURL(): redis://172.17.0.2"
time="2020-05-19T19:17:33Z" level=debug msg="connected to: 172.17.0.2"
time="2020-05-19T19:17:33Z" level=debug msg="connecting took 0.000598 seconds"
time="2020-05-19T19:17:33Z" level=debug msg="c.Do() - running command: CLIENT [SETNAME redis_exporter]"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - err: read tcp 172.17.0.3:55110->172.17.0.2:6379: i/o timeout"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - done"
time="2020-05-19T19:17:48Z" level=error msg="Couldn't set client name, err: read tcp 172.17.0.3:55110->172.17.0.2:6379: i/o timeout"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - running command: CONFIG [GET *]"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - err: write tcp 172.17.0.3:55110->172.17.0.2:6379: use of closed network connection"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - done"
time="2020-05-19T19:17:48Z" level=debug msg="Redis CONFIG err: write tcp 172.17.0.3:55110->172.17.0.2:6379: use of closed network connection"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - running command: INFO [ALL]"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - err: write tcp 172.17.0.3:55110->172.17.0.2:6379: use of closed network connection"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - done"
time="2020-05-19T19:17:48Z" level=debug msg="Redis INFO err: write tcp 172.17.0.3:55110->172.17.0.2:6379: use of closed network connection"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - running command: INFO []"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - err: write tcp 172.17.0.3:55110->172.17.0.2:6379: use of closed network connection"
time="2020-05-19T19:17:48Z" level=debug msg="c.Do() - done"
time="2020-05-19T19:17:48Z" level=error msg="Redis INFO err: write tcp 172.17.0.3:55110->172.17.0.2:6379: use of closed network connection"
time="2020-05-19T19:17:48Z" level=debug msg="scrapeRedisHost() done"
```

The error logs that come here aren't the same as those in production. :(
Which makes me think, it might not be due to a long running command.

**Comment by shubhambhattar** [comment] 2020-05-19 19:25
I also repeated the experiment with `redis_exporter:v1.5.2` which is running in production and this is what I got:

```
 $ docker run --rm -p 9121:9121 --name redis_exporter oliver006/redis_exporter:v1.5.2 --redis.addr 172.17.0.2
Unable to find image 'oliver006/redis_exporter:v1.5.2' locally
v1.5.2: Pulling from oliver006/redis_exporter
8d5b4ea720d8: Pull complete 
bb4b7eb76078: Pull complete 
Digest: sha256:d52aebf0ff162b5b953dfe7dfcb8a319748654fd7325007d93d2884e027edd2d
Status: Downloaded newer image for oliver006/redis_exporter:v1.5.2
time="2020-05-19T19:22:42Z" level=info msg="Redis Metrics Exporter v1.5.2    build date: 2020-03-16-20:50:18    sha1: 18080da36b0a97595d308cfb4bdf92eb1e396c44    Go: go1.14    GOOS: linux    GOARCH: amd64"
time="2020-05-19T19:22:42Z" level=info msg="Providing metrics at :9121/metrics"
time="2020-05-19T19:23:10Z" level=error msg="Couldn't set client name, err: read tcp 172.17.0.3:55142->172.17.0.2:6379: i/o timeout"
time="2020-05-19T19:23:10Z" level=error msg="Redis INFO err: write tcp 172.17.0.3:55142->172.17.0.2:6379: use of closed network connection"

```

These logs are different than the ones in my production setup (mentioned in the comment: [https://github.com/oliver006/redis_exporter/issues/386#issuecomment-630966013](https://github.com/oliver006/redis_exporter/issues/386#issuecomment-630966013))

**Comment by oliver006** [comment] 2020-05-20 15:15
Ok, so looks like redis is not accepting new connections while it's hanging on a long-running query.
I guess that makes sense, I believe Redis (version 5 for sure) is single-threaded so it wouldn't be able to accept the new connection as it's busy working on your really long query (or the DEBUG SLEEP command).

**Comment by shubhambhattar** [comment] 2020-05-20 15:52
@oliver006 I don't think Redis is running a long running operation because:

- From the analysis that I did yesterday, the logs that came in production (posted above in comments) and the logs when I simulated `DEBUG SLEEP X` command (also posted above in comments) are different.

- I checked Slowlog of Redis and there were no commands that took more than 15ms.

**Comment by oliver006** [comment] 2020-05-20 15:58
Ok, makes sense.
But in that case it's hard to say what's going on unless you can run your prod redis_exporter with the `--debug` flag and drill further into what the issue is.

**Comment by shubhambhattar** [comment] 2020-05-20 21:20
@oliver006 Got your point. Enabling `--debug` in prod is a bit tricky because we'll have to restart the service. Will try to dig deep in this and post here if I find something relevant.

**Comment by oliver006** [comment] 2020-05-21 02:20
Thanks @shubhambhattar

**Comment by oliver006** [comment] 2020-06-24 03:00
Closing - please re-open as needed.

**Closed by oliver006** 2020-06-24 03:00 UTC
Labels: question
