### ISSUE TITLE
Password cannot contain colon

### ISSUE THREAD

**Issue by apsega** [oliver006/redis_exporter#160] opened 2018-05-25 18:08 UTC
Hey,

Facing an issue if my redis password contains a colon:

```
time="2018-05-25T17:59:45Z" level=debug msg="Trying DialURL(): <IP>:<PORT>"
time="2018-05-25T17:59:45Z" level=debug msg="DialURL() failed, err: parse <IP>:<PORT>: first path segment in URL cannot contain colon"
time="2018-05-25T17:59:45Z" level=debug msg="Trying: Dial(): tcp <IP>:<PORT>"
time="2018-05-25T17:59:45Z" level=debug msg="aborting for addr: <IP>:<PORT> - redis err: ERR invalid password"
```

Auth works using `redis-cli`.

**Comment by oliver006** [comment] 2018-05-27 22:44
There's an (undocumented) flag called `--separator` (see here: https://github.com/oliver006/redis_exporter/blob/master/main.go#L22) - can you try setting that e.g. `|` and see if it works?

**Comment by apsega** [comment] 2018-05-29 05:08
It still doesn't work.. Docke run command:
```
docker run  --restart always --net net1 -d --name redis-exporter -v /etc/redis-exporter:/etc/redis-exporter -p 9121:9121 oliver006/redis_exporter --redis.file=/etc/redis-exporter/redis.txt --separator="@" --debug
```

Logs:
```
time="2018-05-29T05:05:24Z" level=debug msg="Trying DialURL(): <IP>:6379"
time="2018-05-29T05:05:24Z" level=debug msg="DialURL() failed, err: parse <IP>:6379: first path segment in URL cannot contain colon"
time="2018-05-29T05:05:24Z" level=debug msg="Trying: Dial(): tcp <IP>:6379"
time="2018-05-29T05:05:24Z" level=debug msg="aborting for addr: <IP>:6379 - redis err: ERR invalid password"
```

**Comment by oliver006** [comment] 2018-05-29 12:03
From your logs:
`time="2018-05-29T05:05:24Z" level=debug msg="Trying DialURL(): <IP>:6379"`

`<IP>:6379` doesn't look like a valid IP to me.

**Comment by apsega** [comment] 2018-05-29 12:04
Sorry for not being clear, I've replaced true IP with `<IP>` for some concerns. I've also tried using `|` as a seperator.

**Comment by oliver006** [comment] 2018-05-30 02:41
Ah ok, thanks for clarifying. I'll look into it more the upcoming days and update it by the weekend.

**Comment by oliver006** [comment] 2018-06-08 07:30
I just tried the following and it works:

bring up a docker redis container with a password:
`docker run --name redis-pwd  -p 6380:6379 -e REDIS_PASSWORD=password,123 bitnami/redis:latest`

Confirm a password is set and the password is `password,123`:

```
➜  ~ redis-cli -p 6380
Could not connect to Redis at 127.0.0.1:6380: Connection refused
Could not connect to Redis at 127.0.0.1:6380: Connection refused
not connected> exit
➜  ~ redis-cli -p 6380
127.0.0.1:6380> auth password,123
OK
127.0.0.1:6380> info
# Server
redis_version:4.0.9
redis_git_sha1:00000000
redis_git_dirty:0

...
```

I now run the exporter: (latest master branch)

`go run main.go -redis.password="password,123"  --debug -redis.addr="redis://localhost:6380" -separator="@"`

and can pull the metrics just fine:

```
➜  ~ curl -s localhost:9121/metrics | grep up
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 9
# HELP redis_up
# TYPE redis_up gauge
redis_up{addr="redis://localhost:6380",alias=""} 1
# HELP redis_uptime_in_seconds
# TYPE redis_uptime_in_seconds gauge
redis_uptime_in_seconds{addr="redis://localhost:6380",alias=""} 166
➜  ~
```

**Comment by oliver006** [comment] 2018-06-08 08:21
Ok, I think I figured out what the problem is.

When you use the CSV file to supply redis hosts and passwords  the separator setting isn't used and you need to make sure you properly quote the fields in the file. E.g.:
```
$ cat redis-file.txt
"redis://localhost:6380","password,123",alias
```

This is not clear from the docs and should be explained better but for now just let me know if that works for you and then we can update the docs later.

**Comment by apsega** [comment] 2018-06-08 14:27
Still doesn't work. Maybe because of other characters in a password? Here's my `redis.txt`:
```
"127.0.0.1:6379","xxxxxxxxxxxx#;xxxxxxx':'xxxx=xx$xxxxxx",redis1
```
Again running the following docker run command:
```
docker run  --restart always --net net1 -d --name redis-exporter -v /etc/redis-exporter:/etc/redis-exporter -p 9121:9121 oliver006/redis_exporter -redis.file=/etc/redis-exporter/redis.txt -separator="@" -debug
```

**Comment by oliver006** [comment] 2018-06-11 21:18
Hmm, yeah, no idea what's going on, sorry.

**Comment by apsega** [comment] 2018-06-25 17:40
So there's no workarounds?

**Comment by oliver006** [comment] 2018-06-25 20:28
I don't know. I have trouble reproducing the problem but you can reproduce it so clearly there's something broken.
You could try a different password without quotes if that's an option.

**Comment by oliver006** [comment] 2018-06-25 20:28
Other than that I'm out of ideas right now, sorry.

**Comment by oliver006** [comment] 2018-07-25 20:37
Closing this, please reopen if you have more instructions how to reproduce this.

**Closed by oliver006** 2018-07-25 20:37 UTC
