### ISSUE TITLE
Ingesting keys with slashes into prometheus

### ISSUE THREAD

**Issue by WimDeMeester** [oliver006/redis_exporter#850] opened 2023-11-09 15:35 UTC
**Describe the problem**
I'm trying to include a lot of keys which have a name like 

`/elt/telif/target/coord/velocity_offset_radec`

I try to add all the keys using the following command:

`redis_exporter --redis.addr=127.0.0.1:6379 --check-keys /elt*`

In the output, I can see that all the keys are found:

```
redis_key_size{db="db0",key="/elt/telif/target/coord/proper_motion_radec"} 39
redis_key_size{db="db0",key="/elt/telif/target/coord/radvel"} 31
redis_key_size{db="db0",key="/elt/telif/target/coord/rshift"} 31
```

However, I don't see the real values added.  So no redis_key_value or redis_key_value_as_string can be seen in the stdout when starting up redis_exporter.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[x] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)

`redis_exporter --redis.addr=127.0.0.1:6379 --check-keys /elt*`

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 
Did you upgrade from 0.3x.x to 1.0 and are scraping multiple hosts? [Have a look here ](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) how the configuration changed.

I expect to have all the values for keys which look like `/elt/telif/target/coord/velocity_offset_radec`.

**Screenshots**

**Additional context**

**Comment by oliver006** [comment] 2023-11-15 05:04
Not sure why the values don't get picked up. Could you try with the `--debug` flag?

**Comment by WimDeMeester** [comment] 2023-11-15 10:14
I get the following messages:

```
DEBU[0416] c.Do() - running command: SELECT [0]         
DEBU[0416] c.Do() - done                                
DEBU[0416] c.Do() - running command: TYPE [/elt/met/fcs/devices/wcu-ccdm/lcs/axis_enable] 
DEBU[0416] c.Do() - done                                
DEBU[0416] c.Do() - running command: PFCOUNT [/elt/met/fcs/devices/wcu-ccdm/lcs/axis_enable] 
DEBU[0416] c.Do() - err: WRONGTYPE Key is not a valid HyperLogLog string value. 
DEBU[0416] c.Do() - done                                
DEBU[0416] c.Do() - running command: STRLEN [/elt/met/fcs/devices/wcu-ccdm/lcs/axis_enable] 
DEBU[0416] c.Do() - done                                
DEBU[0416] c.Do() - running command: GET [/elt/met/fcs/devices/wcu-ccdm/lcs/axis_enable] 
DEBU[0416] c.Do() - done                                
DEBU[0416] registerConstMetric( key_value_as_string , 1.00) err: label value "\x9fV%\xf2\xfe\u0097\x17\x00\x00\n\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00" is not valid UTF-8 

```

**Comment by oliver006** [comment] 2023-11-19 17:01
Interesting, let me try if I can reproduce this locally.

**Comment by oliver006** [comment] 2024-04-21 03:50
I just tried this (I know, it's been a LONG time) but couldn't reproduce this.

In Redis I set a key like this:
```
set /elt/telif/target/coord/sup 0.000463
```

and then ran

```
go run . --debug --redis.addr=127.0.0.1:16384 --check-keys "/elt*"
```

and in the metrics I get:

```
# HELP redis_key_size The length or size of "key"
# TYPE redis_key_size gauge
redis_key_size{db="db0",key="/elt/telif/target/coord/sup"} 8
redis_key_size{db="db0",key="/elt/telif/target/coord/velocity_offset_radec"} 2
# HELP redis_key_value The value of "key"
# TYPE redis_key_value gauge
redis_key_value{db="db0",key="/elt/telif/target/coord/sup"} 0.000463
```

I tried this with `redis:7.0` and the current version of the redis_exporter.

I'm going to close this but feel free to re-open if you think there is still something wrong

**Closed by oliver006** 2024-04-21 03:50 UTC
Labels: bug
