### ISSUE TITLE
unsafe map write when -include-system-metrics flag enabled

### ISSUE THREAD

**Issue by youngchul** [oliver006/redis_exporter#269] opened 2019-06-07 08:28 UTC
Hi,

I'm reporting a concurrency issue of the variable `metricMapGauges` when `-include-system-metrics` flag is enabled. I think the global map type variable should be protected because it is read throughout the code and only updated if the flag is enabled.
https://github.com/oliver006/redis_exporter/blob/v1.0.0/exporter.go#L278-L280

I'm running an instance of v1.0.0 with several hundred of targets. With `-include-system-metrics` flag enabled, the instance crashes with the following errors. With the flag disabled, it works as expected.
```
fatal error: concurrent map iteration and map write
goroutine 122 [running]:
runtime.throw(0x8b31a5, 0x26)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0000badc8 sp=0xc0000bad98 pc=0x42c8a2
runtime.mapiternext(0xc0000baed8)
/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc0000bae50 sp=0xc0000badc8 pc=0x40eba7
main.(*Exporter).Describe(0xc0000c4fc0, 0xc00015e720)
/usr/local/src/redis_exporter/exporter.go:324 +0x210 fp=0xc0000bafa8 sp=0xc0000bae50 pc=0x7b7eb0
github.com/prometheus/client_golang/prometheus.(*Registry).Register.func1(0x93aaa0, 0xc0000c4fc0, 0xc00015e720)
```
```
fatal error: concurrent map read and map write
goroutine 16 [running]:
runtime.throw(0x8b083f, 0x21)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000077798 sp=0xc000077768 pc=0x42c8a2
runtime.mapaccess2_faststr(0x823080, 0xc00017a0f0, 0xc00040c7f2, 0x12, 0xc000188140, 0xc000417520)
/usr/local/go/src/runtime/map_faststr.go:116 +0x4a9 fp=0xc000077808 sp=0xc000077798 pc=0x412829
main.includeMetric(0xc00040c7f2, 0x12, 0xc00040c7f2)
/usr/local/src/redis_exporter/exporter.go:367 +0x80 fp=0xc000077848 sp=0xc000077808 pc=0x7b86b0
main.(*Exporter).extractInfoMetrics(0xc0000c4ea0, 0xc000020c60, 0xc00040c000, 0xea1, 0x10, 0xea1, 0x0)
/usr/local/src/redis_exporter/exporter.go:646 +0xecf fp=0xc000077d20 sp=0xc000077848 pc=0x7bb48f
main.(*Exporter).scrapeRedisHost(0xc0000c4ea0, 0xc000020c60, 0x0, 0x0)
/usr/local/src/redis_exporter/exporter.go:1054 +0x4f6 fp=0xc000077e38 sp=0xc000077d20 pc=0x7c0596
```

**Comment by oliver006** [comment] 2019-06-07 13:35
Thanks for the bug report, that's a good catch.

I think i know what the problem is, `metricMapGauges` is a global variable and written to all over when used with multiple instances.
Let me see that I can get that fixed by making it a part of the `Exporter` struct.

**Closed** 2019-06-07 16:03 UTC

**Comment by oliver006** [comment] 2019-06-07 16:05
Released as https://github.com/oliver006/redis_exporter/releases/tag/v1.0.1
