### ISSUE TITLE
v0.31.0: redis_master_last_io_seconds missing from metrics

### ISSUE THREAD

**Issue by itmecho** [oliver006/redis_exporter#245] opened 2019-03-22 11:36 UTC
I was running the previous version (v0.30.0) and had setup a Grafana dashboard to track various metrics about our redis cluster. The pod with the exporter restarted last night and I had made the mistake of not specifying an image tag so it pulled the latest version (v0.31.0). Once that exporter was running, my dashboard was showing no data points for the `redis_master_last_io_seconds` metric. I checked the metrics endpoint and the metrics was missing.

I set the version tag to the previous version and the metrics reappeared.

**Comment by jobec** [comment] 2019-03-22 12:25
I noticed the same but then for `master_repl_offset` on the master.

It looks like #238 caused all replication keys not starting with `slave\d+` to be ignored.

**Comment by oliver006** [comment] 2019-03-22 13:01
Thanks for reporting this, I think I see at least 1 or 2 issues with how I refactored that section in #238 
I'll put up a PR in a few to try to address those.
I'll also see that I can amend the tests so a bug like this won't slip past them in the future.

**Comment by oliver006** [comment] 2019-03-22 13:04
fyi: PR #246

**Comment by oliver006** [comment] 2019-03-22 18:35
I merged #246 and added some more tests to ensure presence of e.g. `master_repl_offset` and `test_master_last_io_seconds`.
It has been released as https://github.com/oliver006/redis_exporter/releases/tag/v0.32.0 - can you confirm that version works for you?

**Comment by jobec** [comment] 2019-03-22 19:49
I can confirm both `redis_master_last_io_seconds` and `master_repl_offset` metrics are back.

**Comment by oliver006** [comment] 2019-03-22 21:50
Thanks @jobec !

**Closed by oliver006** 2019-03-22 21:50 UTC
